### PR TITLE
Add nuget push on build

### PR DESCRIPTION
**Pull request by stimms**

### CODE REVIEW

**Comment by dpaquette** [comment]
is this what we want? A new version on Nuget for every commit to master?

**Comment by stimms** [comment]
My feeling is "yes". We don't really roll out enough changes to make it particularly unstable.

**Comment by dpaquette** [comment]
I guess... A more common approach is to tie the Nuget deployment to release tags.

**Comment by stimms** [comment]
HAHAHA approving my own PR

**Pull request merged**
