### PR TITLE
File scoped namespaces

### PR DESCRIPTION
**Pull request by xperiandri**
Migrated to file-scoped namespaces

### CODE REVIEW

**Comment by dpaquette** [comment]
@xperiandri  This looks great but we have merge conflicts now that we have the previous PR merged. Can you create a new PR that contains only your [f55e267](https://github.com/MisterJames/GenFu/pull/167/commits/f55e26787a653c49d49bea7a3ccf5a9e4cf595f3) commit?

**Comment by xperiandri** [comment]
Done

**Review by dpaquette — APPROVED** [review]

**Comment by dpaquette** [comment]
@xperiandri  This looks great but I think the rename of province / state abbreviations is causing some failed tests

**Comment by xperiandri** [comment]
Fixed

**Comment by dpaquette** [comment]
🎉 
Thanks so much for your contributions to GenFu!

**Pull request merged**
