### PR TITLE
Bugfix/25 inherited properties

### LINKED ISSUE #25: Configuring inherited properties not working
```
public class BaseThing 
{
   public int Id {get; set;}
}

public class OtherThing  : BaseThing
{
}
```

Configuring the child class as follows doesn't work:
```A.Configure<OtherThing>().Fill(a => a.Id, () => 0) ```

But this does:
```A.Configure<BaseThing>().Fill(a => a.Id, () => 0) ```

Would be great if both worked properly.

### PR DESCRIPTION
**Pull request by stimms**
This fixes #25

### CODE REVIEW

**Comment by dpaquette** [comment]
Great fix! :shipit:

**Comment by stimms** [comment]
Well maybe. I haven't tested it but if you create 2 descendants of a base class then set up two fills for a common property I'm not sure what would happen.

**Comment by dpaquette** [comment]
I just saw the unit tests that tested the exact case that was broken and got excited. Perhaps some additional tests are needed for these more complex scenarios

**Comment by stimms** [comment]
Well that seemed to work... so I guess :shipit:

**Comment by dpaquette** [comment]
Magic!

**Pull request merged**
